### ISSUE TITLE
can't go pass registration

### ISSUE THREAD

**Issue by guylouis** [mul1sh/easy-print#1]
Hey! I don't manage to create an account with the app and get stuck in a 'please wait' screen while trying to register a new account

**Comment by mul1sh** [comment]
@guylouis  sorry for this and the late reply just waking up after a long night of hacking 😅 

Anyway the failure to login is because on an heroku dyno failure (last minute issue's 😢. This heroku instance holds the database and the web server for registration so thats why you can't register :(.

But still I can fix this by moving the above backend to an aws instance and then I'll build another apk pointing to this server  and upload it for you to test. Is this ok for you?

**Comment by guylouis** [comment]
sure !

**Comment by mul1sh** [comment]
Cool let me resuming working on it then, will send the apk in a few 😀👍

**Comment by mul1sh** [comment]
@guylouis an update to this, I finally have the aws instance up and running. Working on deploying the backend now and the I rebuild the app pointing to this server and send over the apk.

Also should I update my repo with the commits I did not push yesterday, so that you can also see the code for the keycard integration + crypto payments?

**Comment by guylouis** [comment]
> Also should I update my repo with the commits I did not push yesterday, so that you can also see the code for the keycard integration + crypto payments?

yes would be great ! thanks

**Comment by guylouis** [comment]
hey @mul1sh 
what's up ?  can we try your work ? it seems super interesting and is definitely a direction we want to help keycard to go (use it in for payments)

**Comment by mul1sh** [comment]
@guylouis sorry i'm unable to finish deploying the backend right now because of work constraints so i've put this app on hold.

But still sure i'll resume working on it in like 3 weeks or so and probably make everything dencentralized and avoid all this backend server stuff 😅 and then i'll alert you to test and check the app.

**Comment by guylouis** [comment]
awesome, looking forward to it !
ping us here or on status channel #status-keycard https://get.status.im/chat/public/status-keycard

**Comment by mul1sh** [comment]
@guylouis will do, btw can I get a keycard to test with? I'm using a java-card sim to test with but would a real keycard to work with as well. Thanks.

**Comment by guylouis** [comment]
sure, I just need a way to mp you

**Comment by mul1sh** [comment]
Ok let me reach out via twitter and I've also pinged in the status-keycard chatroom too. Thanks.
